// LETTER_BOX_WRITING_V3_20260913
function practiceTarget(w,q){return q.stage===3?{text:w.word.slice(q.r.start,q.r.end),start:q.r.start,end:q.r.end}:{text:w.word,start:0,end:w.word.length}}
function alignChars(target,typed){target=norm(target);typed=norm(typed);let n=target.length,m=typed.length,d=Array.from({length:n+1},()=>Array(m+1).fill(0));for(let i=0;i<=n;i++)d[i][0]=i;for(let j=0;j<=m;j++)d[0][j]=j;for(let i=1;i<=n;i++)for(let j=1;j<=m;j++)d[i][j]=Math.min(d[i-1][j-1]+(target[i-1]===typed[j-1]?0:1),d[i-1][j]+1,d[i][j-1]+1);let slots=Array(n),extras=[],i=n,j=m;while(i||j){let diag=i&&j?d[i-1][j-1]+(target[i-1]===typed[j-1]?0:1):1e9;if(i&&j&&d[i][j]===diag){let same=target[i-1]===typed[j-1];slots[i-1]={expected:target[i-1],typed:typed[j-1],typedIndex:j-1,insertAt:j-1,state:same?'ok':'bad'};i--;j--;continue}if(i&&d[i][j]===d[i-1][j]+1){slots[i-1]={expected:target[i-1],typed:'',typedIndex:null,insertAt:j,state:'missing'};i--;continue}if(j){extras.push({char:typed[j-1],typedIndex:j-1,before:i});j--}}return{slots,extras:extras.reverse(),typed}}
function writingTiles(w,q){let p=practiceTarget(w,q),raw=norm(q.answer),a=alignChars(p.text,raw),bad=!!q.feedback?.bad,h=q.hint?.fullIndex,out=[],next=raw.length<p.text.length?p.start+raw.length:-1;for(let j=0;j<w.word.length;j++){if(q.stage===3&&(j<p.start||j>=p.end)){out.push(`<span class="lettertile fixed">${w.word[j]}</span>`);continue}let rel=j-p.start,slot=a.slots[rel],shown='',cls='';if(bad){shown=slot?.typed||'';cls=slot?.state==='ok'?'ok':slot?.state==='bad'?'bad':'missing'}else{shown=raw[rel]||'';cls=shown?'filled':'';if(!q.hint&&j===next)cls+=' active'}if(j===h)cls+=' hintfocus';out.push(`<span class="lettertile ${cls.trim()}">${esc(shown)}</span>`)}return out.join('')}
function inlineHint(w,q){let h=q.hint;if(!h)return'<div id="inlineHint"></div>';if(h.kind==='remove')return`<div class="inlinehint" id="inlineHint"><div class="hintlead">✨ This extra letter does not belong.</div><div class="hintprompt">The purple box shows where the spelling got off track.</div><div class="hchoices"><button class="removechoice" data-removehint="1">Remove “${esc(h.extraChar)}”</button></div><button class="hintbackbtn" id="hintBack">Keep writing</button></div>`;return`<div class="inlinehint" id="inlineHint"><div class="hintlead">✨ Fix the purple box</div><div class="hintprompt">Letter ${h.fullIndex+1} of ${w.word.length} · Which letter belongs here?</div><div class="hchoices">${h.options.map(x=>`<button data-h="${x}">${x}</button>`).join('')}</div><button class="hintbackbtn" id="hintBack">Keep writing</button></div>`}
function answer(w,q){let r=q.r;if(q.stage===1)return`<div class="choices">${q.choices.map(c=>`<button class="choice ${q.wrong.includes(c)?'wrong':''}" data-c="${c}">${c}</button>`).join('')}</div>`;if(q.stage===2)return`<div class="gap"><span>${w.word.slice(0,r.start)}</span><span class="blank">${'_'.repeat(r.end-r.start)}</span><span>${w.word.slice(r.end)}</span></div><div class="choices">${q.choices.map(c=>`<button class="choice ${q.wrong.includes(c)?'wrong':''}" data-c="${c}">${c}</button>`).join('')}</div>`;return`<div class="spellwrap"><div class="spellinput"><div class="tileword" id="tileword" style="--letters:${w.word.length}">${writingTiles(w,q)}</div><input id="write" class="scribbleCapture" value="${esc(q.answer)}" inputmode="text" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" aria-label="Write the spelling here"></div><div class="handtip">✎ <b>Write across the boxes</b> with Apple Pencil — one letter will land in each box.</div>${inlineHint(w,q)}</div><button class="check" id="check">Check</button>`}
function feedback(w,q){if(!q.feedback)return'';if(!q.feedback.bad)return'<div class="feedback good"><div><b>Yes! 🌱</b><small>That spelling is growing strong.</small></div></div>';return`<div class="feedback"><div><b>Almost — check the colored boxes.</b><small>Green is right. Red needs another try. Hint will point to one box.</small></div><button id="again">Try again</button></div>`}
function refreshTiles(w,q){let t=$('#tileword');if(t)t.innerHTML=writingTiles(w,q)}
function bindPlay(w,q){$('#listen')?.addEventListener('click',()=>speak(w,false));$$('[data-c]').forEach(b=>b.onclick=()=>pick(b.dataset.c));let i=$('#write');if(i){i.oninput=e=>{let p=practiceTarget(w,q);q.answer=norm(e.target.value).slice(0,p.text.length);e.target.value=q.answer;q.feedback=null;q.hint=null;$$('.feedback,.letters').forEach(x=>x.remove());let ih=$('#inlineHint');if(ih)ih.innerHTML='';refreshTiles(w,q)};i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check()}}}$('#check')?.addEventListener('click',check);$('#again')?.addEventListener('click',()=>{q.feedback=null;q.hint=null;playView()});$('#hintBack')?.addEventListener('click',()=>{q.hint=null;playView()});$$('[data-h]').forEach(b=>b.onclick=()=>chooseHint(b.dataset.h,b));$('[data-removehint]')?.addEventListener('click',removeHintExtra);$$('[data-s]').forEach(b=>b.onclick=()=>help(b.dataset.s,w,q))}
function check(){let q=P.q,w=S.lib[q.id];q.answer=norm($('#write')?.value||q.answer);let correct=q.stage===3?w.word.slice(q.r.start,q.r.end):w.word;if(norm(q.answer)===norm(correct))right(w,q);else{wrong(w,q,q.answer,correct,q.stage===3?q.r.start:0);q.feedback={bad:true,typed:q.answer};q.hint=null;playView();tone('wrong')}}
function makeHint(w,q){let p=practiceTarget(w,q),a=alignChars(p.text,q.answer),idx=a.slots.findIndex(x=>x&&x.state!=='ok');if(idx<0&&a.extras.length){let ex=a.extras[0],full=p.start+Math.min(ex.before,p.text.length-1);return{kind:'remove',typedIndex:ex.typedIndex,extraChar:ex.char,fullIndex:Math.max(p.start,full)}}if(idx<0)idx=Math.min(norm(q.answer).length,p.text.length-1);idx=Math.max(0,idx);let slot=a.slots[idx]||{expected:p.text[idx],typedIndex:null,insertAt:idx,state:'missing'},correct=p.text[idx],fullIndex=p.start+idx,last=norm(w.learn.lastWrong||''),old=q.stage===3?last[idx]||'':last[fullIndex]||'',typed=slot.typed||'',map={b:['p','d'],p:['b','d'],d:['b','t'],e:['i','a'],i:['e','y'],y:['i','e'],c:['k','s'],k:['c','g'],s:['c','z'],t:['d','f'],a:['e','o'],o:['a','u'],u:['o','a'],l:['r','i'],r:['l','n'],g:['j','c'],h:['w','n']},alts=[];if(typed&&typed!==correct)alts.push(typed);if(old&&old!==correct)alts.push(old);for(let x of (map[correct]||['a','e','i']))if(x&&x!==correct)alts.push(x);alts=[...new Set(alts)];while(alts.length<2){let x='abcdefghijklmnopqrstuvwxyz'[(fullIndex+alts.length*7)%26];if(x!==correct&&!alts.includes(x))alts.push(x)}return{kind:'letter',relIndex:idx,fullIndex,correct,options:shuffle([correct,...alts.slice(0,2)])}}
function openInlineHint(w,q){w.learn.hints++;save();speak(w,true);q.hint=makeHint(w,q);playView();setTimeout(()=>$('#write')?.blur(),140)}
function chooseHint(c,btn){let q=P.q,w=S.lib[q.id],h=q.hint;if(!h||h.kind!=='letter')return;if(c!==h.correct){tone('wrong');btn?.classList.remove('nope');if(btn){void btn.offsetWidth;btn.classList.add('nope')}return}let p=practiceTarget(w,q),a=alignChars(p.text,q.answer),slot=a.slots[h.relIndex]||{},chars=[...norm(q.answer)];if(slot.typedIndex==null)chars.splice(slot.insertAt??h.relIndex,0,c);else chars[slot.typedIndex]=c;q.answer=chars.join('').slice(0,p.text.length);q.hint=null;q.feedback=null;tone('right');playView()}
function removeHintExtra(){let q=P.q,w=S.lib[q.id],h=q.hint;if(!h||h.kind!=='remove')return;let p=practiceTarget(w,q),chars=[...norm(q.answer)];chars.splice(h.typedIndex,1);q.answer=chars.join('').slice(0,p.text.length);q.hint=null;q.feedback=null;tone('right');playView()}
function help(t,w,q){if(t==='peek'){w.learn.peeks++;save();speak(w,true);let e=document.createElement('div');e.className='peek';e.innerHTML=`<b>${w.word}</b>`;document.body.appendChild(e);setTimeout(()=>e.remove(),2050);return}if(t==='hint'){openInlineHint(w,q);return}support=support===t?'':t;playView()}
