'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const js=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('fluent-play-v29.css','utf8');
const between=(start,end)=>{const a=js.indexOf(start),b=js.indexOf(end,a+start.length);assert(a>=0&&b>a,`Could not find ${start}`);return js.slice(a,b)};
const music=between('function scheduleBgmBar(){','function alignChars(');
assert(music.includes("currentView!=='garden'"),'BGM scheduling and starting must exclude Play');
assert(music.includes("state.settings.music&&currentView==='garden'"),'Only Garden can request BGM');
assert(music.includes('stopBgm()'),'Leaving Garden stops BGM');
assert(!music.includes('state.settings.sound=false'),'Audio and effects setting are not muted');
const play=between('function renderTask(){','function hintHtml(');
assert(play.includes('function stage4HandwritingHtml(w,q)'),'Stage 4 has a distinct full-word view');
assert(play.includes('if(q.stage===4)return stage4HandwritingHtml(w,q)'),'Stage 4 uses its own view');
assert(play.includes('id="stage4Answer"')&&play.includes('inputmode="none"')&&play.includes('spellcheck="false"'),'Full-word writing supports Pencil without keyboard or auto spelling');
assert(play.includes('id="stage4ClearBtn"')&&play.includes('id="checkAnswerBtn"'),'Stage 4 can clear and explicitly check');
assert(play.includes('id="letterRow"')&&play.includes('class="letter-box'),'Stage 3 keeps guided boxes');
assert(!play.includes('q.stage===4?\'Write one letter in each box'),'Stage 4 instructions are updated');
const binder=between('function bindQuestion(w,q){','function bindTraceBox(');
assert(binder.includes('if(q.stage===4)'),'Dedicated Stage 4 handler');
assert(binder.includes("input.addEventListener('input',e=>store(!e.isComposing))")&&binder.includes("'compositionend'"),'Full-word field preserves Scribble composition');
assert(binder.includes('weeklyAnswerText(input.value,w.word)'),'Stage 4 uses lower-case, symbol-free answer handling');
assert(binder.includes('q.fullAnswer=cleaned')&&binder.includes("$('#stage4ClearBtn').onclick"),'Whole-word editing and clearing are retained');
assert(binder.includes('return\n  }')||binder.includes('blur?.();return'),'Stage 4 does not accidentally bind Stage 3 boxes');
assert(css.includes('caret-color:transparent!important')&&css.includes('.stage4-full-answer'),'Full word visually suppresses blinking caret');
const trace=between('function bindTraceBox(','function startFilledBoxScratch(');
assert(trace.includes('trace-retry'), 'Stage 3 tracing retained');
assert(trace.includes('140'), 'Stage 3 retry indicator clears quickly');
const letters=between('function bindLetterBox(','function focusLetter(');
assert(letters.includes('if(hadFeedback)'),'Stage 3 skips expensive DOM cleanup for ordinary letters');
assert(letters.includes('box.focus({preventScroll:true})'),'Pencil can start next box without automatic focus delay');
assert(letters.includes('e.target.replaceWith(written)'),'Completed Stage 3 letters remain clearly visible');
const score=between('function checkHandwriting(','function wrong(');
assert(score.includes("q.stage===4?weeklyAnswerText($('#stage4Answer')?.value??q.fullAnswer,w.word)"),'Stage 4 grades final full-word field, not per-character slots');
assert(score.includes("q.stage===4){q.fullAnswer=attempt;q.letters=[...attempt]"),'Stage 4 attempt is synchronized for review and hints');
assert(score.includes("else{wrong(w,q,attempt,correct)"),'Wrong answers still update learning through the original path');
const pure=between('function weeklyLetterDistance(','function saveWeeklyDraft(');
const field={value:'BEET1E'};let rightCount=0,wrongCount=0;
const ctx={$:selector=>selector==='#stage4Answer'?field:null,expectedText:(w,q)=>q.stage===3?'ai':w.word,right:()=>rightCount++,wrong:()=>wrongCount++,renderTask:()=>{},playSfx:()=>{}};
vm.createContext(ctx);vm.runInContext(pure+'\n'+score,ctx);
const word={word:'beetle'},q={stage:4,fullAnswer:'',letters:[],feedback:null,hint:null};
ctx.checkHandwriting(word,q);
assert.equal(rightCount,1,'Pencil 1 is accepted as l for beetle');
assert.equal(q.fullAnswer,'beetle','Accepted full spelling is canonical lower-case text');
field.value='bee-t!e';ctx.checkHandwriting(word,q);
assert.equal(wrongCount,1,'A genuine misspelling still counts as wrong');
assert.equal(q.fullAnswer,'beete','Punctuation is removed but missing l is not invented');
ctx.checkHandwriting({word:'beetle'},{stage:3,letters:['a','i'],feedback:null,hint:null});
assert.equal(rightCount,2,'Stage 3 continues checking individual gap letters');
const hints=between('function showFullWordHint(w,q){','function showPeek(');
assert(hints.includes('slots[local]?.state===\'missing\''),'Stage 4 hint identifies missing letters');
assert(hints.includes('h.missing?q.fullAnswer.slice(0,at)+h.correct+q.fullAnswer.slice(at)'),'Missing letters are inserted rather than overwriting the next character');
assert(html.includes('fluent-play-v29.css?v=20260917-v29')&&html.includes('app.js?v=20260917-fluent-play-v29'),'Fresh Stage 4 styles and script loaded');
assert(html.includes('v29 · Sep 17'),'Version 29 shown');
assert(html.includes('weekly-test-palm-v25.js?v=20260917-listen-fix-v27'),'Listen and grading palm protection retained');
console.log('PASS v29: Garden-only BGM; Stage 4 fluent handwriting, live edits, final scoring and hints; faster guided Stage 3; old audio and grade protection preserved.');
