'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const src=fs.readFileSync('app.js','utf8');
const page=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('play-flow-v29.css','utf8');
const section=(start,end)=>{const i=src.indexOf(start),j=src.indexOf(end,i+start.length);assert(i>=0&&j>i,`Missing source section ${start}`);return src.slice(i,j)};
const bgm=section('function scheduleBgmBar(){','function alignChars(');
assert(bgm.includes("currentView!=='garden'"),'An in-flight bar does not play on Play or Test');
assert(bgm.includes("currentView==='garden'"),'BGM may start only in Garden');
assert(!bgm.includes("['garden','play'].includes(currentView)"),'Play is excluded from BGM altogether');
assert(bgm.includes('function stopBgm()'),'Leaving Garden still fades and stops the timer');
assert(src.includes("if(!state.settings.sound)return"),'Sound effects stay independently enabled');
const construction=section('function newQuestion(','function confusions(');
assert(construction.includes("fullAnswer:''"),'New Stage 4 questions start with an empty whole-word answer');
const writing=section('function flowComparisonHtml(','function bindTraceBox(');
assert(writing.includes('if(q.stage===4)return fullWordHandwritingHtml(w,q)'),'Stage 4 uses the shared-word writing field');
assert(writing.includes('id="stage4WordInput"'),'Stage 4 uses one input for the whole word');
assert(writing.includes('id="stage3GapInput"'),'Stage 3 uses one input for its short missing chunk');
assert(writing.includes('full>=r.start&&full<r.end'),'Stage 3 retains the dotted non-gap trace cells');
assert(writing.includes('data-guide-full')&&writing.includes('bindTraceBox('),'Trace letter interaction still exists');
assert(writing.includes('weeklyAnswerText(input.value,expectedText(w,q))'),'Both fluent inputs use v28 lowercase normalization');
assert(writing.includes("input.addEventListener('compositionend'"),'Scribble composition is not truncated mid-word');
assert(writing.includes('if(!finishComposition)return'),'Text is cleaned after composition, not per incomplete stroke');
assert(writing.includes("q.stage===3&&q.mode==='erase'"),'Stage 3 erase button clears the new shared gap');
assert(src.includes('if(!q.audioStarted){q.audioStarted=true;'),'A stage speaks automatically once, never on a correction rerender');
assert(writing.includes("e.pointerType==='touch'")&&writing.includes('virtualKeyboard?.hide'),'A finger does not summon the keyboard');
assert(writing.includes('Clear ✎')&&writing.includes('clearFlowBtn'),'Whole-word answer keeps the original Clear control underneath the v30 focus-only replacement');
assert(writing.includes('flowComparisonHtml(answer,w.word)'),'Stage 4 reveals aligned error details only after a wrong check');
assert(writing.includes('flowComparisonHtml(q.letters.join('),'Stage 3 error details apply only after check');
const scoring=section('function checkHandwriting(','function wrong(');
const expectedText=(w,q)=>q.stage===3?w.word.slice(q.range.start,q.range.end):w.word;
const weeklyAnswerText=s=>String(s??'').toLowerCase().replace(/1/g,'l').replace(/[^a-z]/g,'');
const captures=[];const fields={};
const $=key=>fields[key]||null;
const ctx={$,weeklyAnswerText,expectedText,right:(w,q)=>captures.push(['right',q.stage]),wrong:(w,q,attempt,correct)=>captures.push(['wrong',q.stage,attempt,correct]),renderTask:()=>{},playSfx:()=>{},setTimeout:()=>{},session:null,focusRange:()=>({start:0,end:2}),toast:()=>{}};
vm.createContext(ctx);vm.runInContext(scoring,ctx);
const w={word:'ladybug'};
const mk=stage=>({stage,range:{start:4,end:6},letters:['',''],fullAnswer:'',feedback:null,hint:null});
fields['#stage4WordInput']={value:'LADY BUG!',blur(){}};
let q=mk(4);ctx.checkHandwriting(w,q);
assert.deepEqual(captures.pop(),['right',4],'Stage 4 scores the entire cleaned word');
assert.equal(q.fullAnswer,'ladybug');
fields['#stage4WordInput'].value='1adybug';q=mk(4);ctx.checkHandwriting(w,q);
assert.deepEqual(captures.pop(),['right',4],'Stage 4 accepts OCR digit 1 as l only when spelling fits');
fields['#stage4WordInput'].value='ladybg';q=mk(4);ctx.checkHandwriting(w,q);
assert.deepEqual(captures.pop(),['wrong',4,'ladybg','ladybug'],'Missing letters remain genuinely wrong');
fields['#stage3GapInput']={value:'B U!',blur(){}};
q=mk(3);ctx.checkHandwriting(w,q);
assert.deepEqual(captures.pop(),['right',3],'Stage 3 jointly checks its focused two letters');
assert.deepEqual(Array.from(q.letters),['b','u']);
fields['#stage3GapInput'].value='B';q=mk(3);ctx.checkHandwriting(w,q);
assert.deepEqual(captures.pop(),['wrong',3,'b','bu'],'Stage 3 missing letter cannot be ignored');
assert(css.includes('.flow-word-input')&&css.includes('.stage3-gap-flow')&&css.includes('caret-color:transparent'),'Fluent Pencil targets are spacious and have no keyboard caret');
assert(page.includes('play-flow-v29.css?v=20260917-v29')&&page.includes('app.js?v=20260917-learning-groups-v32a'),'Browser loads the current app with v29 writing CSS');
assert(page.includes('v32 · Sep 17'),'Latest visible version keeps the v29 features');
assert(page.includes('weekly-test-palm-v25.js?v=20260917-listen-fix-v27'),'Previously fixed Listen and grading protections remain');
assert(src.includes('reviewMissed:true')&&src.includes('const start=session.reviewMissed?3:'),'Missed-word sessions still enter at Stage 3');
console.log('PASS v29: Garden-only BGM, Stage 4 continuous-word checking, Stage 3 continuous-gap and tracing retained, Scribble composition/normalization, SFX and current practice routing.');
