'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const js=fs.readFileSync('app.js','utf8');
const page=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('weekly-test-v24.css','utf8');
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z]/g,'');
const between=(a,b)=>{const i=js.indexOf(a),j=js.indexOf(b,i+a.length);assert(i>=0&&j>i,`Source missing: ${a}`);return js.slice(i,j)};
const ids=['ladybug','raisin','honeybee','butterfly','beetle','thicket','riding','insect','cricket','grasshopper'];
const lib=Object.fromEntries(ids.map(id=>[id,{id,word:id}]));
const ctx={state:{week:{ids},lib},norm,Set,Object,String};
vm.createContext(ctx);
vm.runInContext(between('function weeklyTestIds(){','function saveWeeklyDraft(){'),ctx);
assert.equal(ctx.weeklyAnswerText('lady bug'),'ladybug');
assert.equal(ctx.weeklyAnswerText('  lady\tbug \n'),'ladybug');
assert.equal(ctx.weeklyAnswerText('honey\u00a0bee'),'honeybee');
assert.equal(ctx.weeklyAnswerText('Rai Sin'),'raisin');
const scored=Array.from(ctx.weeklyScore(ids,{ladybug:'lady bug',raisin:'RAI SIN',honeybee:'honey bee',butterfly:'buter fly'},lib));
assert.equal(scored[0].correct,true);assert.equal(scored[0].answer,'ladybug');
assert.equal(scored[1].correct,true);assert.equal(scored[1].answer,'raisin');
assert.equal(scored[2].correct,true);assert.equal(scored[2].answer,'honeybee');
assert.equal(scored[3].correct,false,'Removing spaces must not forgive an actual missing letter');
assert.equal(scored[4].correct,false,'An unanswered field remains incorrect');
const sheet=between('function renderWeeklyTest(){','function gradeWeeklyTest(){');
const grade=between('function gradeWeeklyTest(){','function renderWeeklyResult(){');
assert(sheet.includes('id="weeklyGradeBtn"')&&sheet.includes('id="weeklyGradeTopBtn"'),'Both bottom and top grading controls are rendered');
assert(sheet.includes("$('#weeklyGradeBtn').onclick=gradeWeeklyTest")&&sheet.includes("$('#weeklyGradeTopBtn').onclick=gradeWeeklyTest"),'Both grading controls work');
assert(sheet.includes('inputmode="none"')&&sheet.includes('virtualkeyboardpolicy="manual"'),'Native Pencil fields suppress software keyboard');
assert(sheet.includes("e.pointerType==='touch'")&&sheet.includes('input.focus({preventScroll:true})'),'Finger focus is prevented and Pencil focus avoids unwanted scrolling');
assert(sheet.includes('storeWeeklyAnswer(!e.isComposing)')&&sheet.includes("'compositionend'"),'Spacing is removed after Scribble commits');
assert(sheet.includes('weeklyAnswerText(input.value,state.lib[id].word)'),'The stored draft is cleaned with its target word');
assert(grade.includes('weeklyAnswerText(input.value,state.lib[input.dataset.id].word)'),'Grading the last active field uses the same normalization');
assert(grade.includes('state.weekTestResult=')&&grade.includes('delete state.weekTestDraft'),'Original grading result and draft completion remain intact');
assert(css.includes('.weekly-test-view .weekly-answer-sheet')&&css.includes('overflow-y:auto')&&css.includes('flex:1 1 auto'),'Only the answer list can scroll under pinned controls');
assert(css.includes('.weekly-sheet-actions #weeklyGradeBtn')&&css.includes('display:inline-flex!important'),'Grade control receives an always-visible button style');
assert(css.includes('caret-color:transparent!important'),'No blinking keyboard caret');
assert(page.includes('weekly-test-v24.css?v=20260917-v24')&&page.includes('app.js?v=20260924-living-c')&&/v[0-9]+ · Sep 24/.test(page),'v24 assets have cache busting and a visible version');
assert(js.includes('const PROD_KEY=')===false,'Test Mode remains a separately loaded script, not duplicated in app.js');
console.log('PASS v24: visible top/bottom grading, independent scroll, no caret, Pencil keyboard suppression, spaces ignored in drafts and grading, true misspellings retained.');
