'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const src=fs.readFileSync('app.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const isolation=fs.readFileSync('test-mode-v21.js','utf8');
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z]/g,'');
const between=(from,to)=>{const a=src.indexOf(from),b=src.indexOf(to,a+from.length);assert(a>=0&&b>a,`Missing source span: ${from}`);return src.slice(a,b)};
const pure=between('function weeklyTestIds(){','function saveWeeklyDraft(){');
const lib={};for(let n=0;n<12;n++){const id=`word${String.fromCharCode(97+n)}`;lib[id]={id,word:id,parentPriority:false};}
lib.extra={id:'extra',word:'extra',parentPriority:true};
const ctx={state:{week:{ids:Object.keys(lib).filter(x=>x!=='extra')},lib},norm,Set,Object,String};
vm.createContext(ctx);vm.runInContext(pure,ctx);
const ids=Array.from(ctx.weeklyTestIds());
assert.equal(ids.length,10,'At most 10 distinct weekly words');
assert.deepEqual(ids,ctx.state.week.ids.slice(0,10),'The test uses weekly words, not starred extra words');
assert.equal(Array.from(ctx.weeklyTestIds()).length,10);
const answers={};ids.forEach(id=>answers[id]=id);answers[ids[1]]='WRONG';answers[ids[2]]='';
const scored=Array.from(ctx.weeklyScore(ids,answers,lib));
assert.equal(scored.length,10);
assert.equal(scored.filter(x=>x.correct).length,8,'Exactly eight correct with one typo and one blank');
assert.equal(scored[1].correct,false);assert.equal(scored[2].answer,'');assert.equal(scored[2].correct,false);
assert.equal(ctx.weeklyScore([ids[0]],{[ids[0]]:ids[0].toUpperCase()},lib)[0].correct,true,'Case-insensitive grading');
assert.equal(scored.every((x,i)=>x.id===ids[i]),true,'Grading preserves sheet order');
const exam=between('// A weekly exam is a separate assessment','function practiceIds(){');
const sheet=between('function renderWeeklyTest(){','function gradeWeeklyTest(){');
const grade=between('function gradeWeeklyTest(){','function renderWeeklyResult(){');
assert(sheet.includes('weekly-answer-sheet')&&sheet.includes('weekly-answer'), 'Ten-row answer sheet rendered');
assert(sheet.includes('autocorrect="off"')&&sheet.includes('spellcheck="false"'), 'Native handwriting without automatic spelling aids');
assert(sheet.includes('data-index')&&sheet.includes('weekly-hear'), 'Each question can be replayed');
assert(!sheet.includes('clueHtml(')&&!sheet.includes('hintHtml(')&&!sheet.includes('w.word'), 'No clue or correct spelling leaked into the answer sheet');
assert(grade.includes('weeklyScore(')&&grade.includes('state.weekTestResult=')&&grade.includes('delete state.weekTestDraft'), 'Single final grading and draft cleanup');
assert(grade.includes('confirm('), 'Blank answers require confirmation');
assert(!exam.includes('.learn=')&&!exam.includes('.weak[')&&!exam.includes('state.xp+='), 'Exam never changes mastery or XP');
assert(exam.includes('wrong.map(x=>x.id)')&&exam.includes('session={count:0,goal:ids.length,ids,'), 'Only missed words feed ordinary four-stage review');
assert(exam.includes('state.weekTestDraft=')&&exam.includes('saveWeeklyDraft()'), 'Draft answers can be saved and resumed');
assert(isolation.includes("const PROD_KEY='mwg-v2-rebuild'")&&isolation.includes("const TEST_KEY='mwg-v2-rebuild-test'")&&isolation.includes('routedKey(this,key)'), 'Existing isolated parent Test Mode remains active');
assert(src.includes('Number(!!b.w.parentPriority)-Number(!!a.w.parentPriority)'), 'Existing starred-word priority retained');
assert(index.includes('weekly-test-v23.css')&&index.includes('weekly-test-v23'), 'HTML loads versioned CSS and app');
assert(index.includes('v23 · Sep 17'),'Visible version updated');
console.log('PASS: weekly-only 10-word selection, grading (typo/blank/case), answer privacy, draft, wrong-only practice, Test Mode isolation, star priority and v23 assets');
