'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const js=fs.readFileSync('app.js','utf8');
const page=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('weekly-lowercase-v28.css','utf8');
const start=js.indexOf('function weeklyTestIds(){');
const stop=js.indexOf('function saveWeeklyDraft(){',start);
assert(start>=0&&stop>start,'Weekly pure normalization functions remain present');
const ids=['ladybug','raisin','beetle','honeybee'];
const lib=Object.fromEntries(ids.map(id=>[id,{id,word:id}]));
const ctx={state:{week:{ids},lib},norm:s=>String(s??'').toLowerCase().replace(/[^a-z]/g,'')};
vm.createContext(ctx);
vm.runInContext(js.slice(start,stop),ctx);
const clean=ctx.weeklyAnswerText;
assert.equal(clean('LADY BUG!', 'ladybug'),'ladybug','Uppercase, spaces, and punctuation become lowercase letters');
assert.equal(clean('  Rai Sin  ', 'raisin'),'raisin','Scribble-added spaces are ignored');
assert.equal(clean('1adybug','ladybug'),'ladybug','Handwritten l misrecognized as digit 1 is restored');
assert.equal(clean('beet1e','beetle'),'beetle','Middle l recognized as 1 is restored');
assert.equal(clean('gra55hopper','grasshopper'),'grahopper','Other digits are removed instead of inventing s characters');
assert.equal(clean('rai!sin?','raisin'),'raisin','Symbols are excluded from answers');
assert.equal(clean('R@I SIN','raisin'),'risin','A missing letter cannot be filled by knowing the expected word');
assert.equal(clean('1','raisin'),'','1 is not blindly accepted as a correct letter where no l belongs');
assert.equal(clean('1','ladybug'),'l','1 can be a lower-case l when supported by the word');
assert.equal(clean('  +-23?!  ','raisin'),'','Only letters can survive numeric/punctuation-only input');
const results=Array.from(ctx.weeklyScore(ids,{ladybug:'1ADY BUG!',raisin:'RAI SIN',beetle:'BEET1E',honeybee:'honeybe3'},lib));
assert.deepEqual(results.map(x=>x.answer),['ladybug','raisin','beetle','honeybe']);
assert.deepEqual(results.map(x=>x.correct),[true,true,true,false]);
assert(js.includes('weeklyAnswerText(draft.answers[id],state.lib[id].word)'),'Saved drafts are normalized when resumed');
assert(js.includes('weeklyAnswerText(input.value,state.lib[id].word)'),'Live Scribble answer is normalized on input');
assert(js.includes('weeklyAnswerText(input.value,state.lib[input.dataset.id].word)'),'Final last-field grading normalizes identically');
assert(js.includes('storeWeeklyAnswer(!e.isComposing)')&&js.includes("'compositionend'"),'IME composition remains visible until commit');
assert(page.includes('app.js?v=20260924-living-c6')&&/v[0-9]+ · Sep 24/.test(page),'Fresh current JS is loaded');
assert(page.includes('weekly-lowercase-v28.css?v=20260917-v28'),'Lowercase visual stylesheet is loaded');
assert(css.includes('.weekly-test-view .weekly-answer')&&css.includes('text-transform:lowercase'),'Writing fields show lowercase');
assert(page.includes('weekly-test-palm-v25.js?v=20260917-listen-fix-v27'),'Listen and grading protection unchanged');
assert(js.includes('reviewMissed:true')&&js.includes('const start=session.reviewMissed?3:'),'Short missed-word review remains');
console.log('PASS v28: lowercase weekly test, contextual 1/l correction, typo integrity, current JS cache, and shortened review retained.');
