'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
(async()=>{
 const helper=fs.readFileSync('word-auto-fill-v34.js','utf8');
 const mockEntries=[{word:'because',meanings:[{partOfSpeech:'conjunction',definitions:[{definition:'For the reason that.',example:'I stayed inside because it rained.'}]}]}];
 const wiki={parse:{wikitext:{'*':'==英語==\n===接続詞===\n# なぜならば、理由を示す。\n==フランス語==\n# autre'}}};
 const requests=[];
 const ctx={window:{},AbortController, setTimeout,clearTimeout,fetch:async url=>{
   requests.push(url);
   if(url.includes('dictionaryapi.dev')&&url.endsWith('/because'))return{ok:true,json:async()=>mockEntries};
   if(url.includes('ja.wiktionary.org')&&url.includes('because'))return{ok:true,json:async()=>wiki};
   return{ok:false,json:async()=>null};
 }};
 vm.createContext(ctx);vm.runInContext(helper,ctx);
 const result=await ctx.window.WordGardenAutoFill.lookup('because');
 assert.equal(result.fields.meaningEn,'For the reason that.');
 assert.equal(result.fields.meaningJa,'なぜならば、理由を示す');
 assert.equal(result.fields.example,'I stayed inside because it rained.');
 assert.equal(result.fields.pictureEmoji,'💭');
 assert.equal(result.sources.meaningEn,'Free Dictionary API');
 const count=requests.length;await ctx.window.WordGardenAutoFill.lookup('because');assert.equal(requests.length,count,'lookup is cached');
 const missing=await ctx.window.WordGardenAutoFill.lookup('notawordzzzz');
 assert.equal(missing.fields.meaningEn,undefined,'unavailable dictionary result must not invent meanings');
 assert.equal(missing.fields.meaningJa,undefined,'unavailable Japanese lookup must not invent translations');
 const app=fs.readFileSync('app.js','utf8');
 const html=fs.readFileSync('index.html','utf8');
 const css=fs.readFileSync('word-auto-fill-v34.css','utf8');
 assert(app.includes("data-fill-group=\\\"week\\\"" )||app.includes('data-fill-group="week"'),'This Week has a bulk action');
 assert(app.includes('data-fill-group="my"')&&app.includes('data-fill-past='),'My Words and past weeks have fill actions');
 assert(app.includes("protectSchoolMeaning:group!=='my'||inCurrentWeek(id)||wordWasInPast(id)"),'school definitions are protected even for overlapping groups');
 assert(app.includes("if(key==='meaningEn'&&protectSchoolMeaning)continue"),'school definitions cannot be overwritten');
 assert(app.includes("if(!value||!autoFieldMissing(w,key))continue"),'filled parent fields stay intact');
 assert(app.includes('const [suggestion,audio]=await Promise.all(['),'dictionary and exact audio are both searched');
 assert(app.includes("if(audio&&isWordOnlyHumanAudio(id,'',audio))"),'ambiguous audio is rejected');
 assert(app.includes("$('#wordInput').addEventListener('change'"),'new My Word automatically searches on word change');
 assert(app.includes("await fillModalBlanks();"),'Save checks missing information before saving');
 assert(app.includes('function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)]'),'backup remains full-state');
 assert(html.indexOf('word-auto-fill-v34.js?v=20260917-v34')<html.indexOf('app.js?v=20260917-auto-fill-v34'),'helper loads before app');
 assert(html.includes('word-auto-fill-v34.css?v=20260917-v34')&&html.includes('v34 · Sep 17'),'UI version and styling updated');
 assert(css.includes('.auto-fill-notice')&&css.includes('.auto-fill-btn'),'Parent has progress and group controls');
 const begin=app.indexOf('// Only sourced suggestions are filled.');const end=app.indexOf('function openWordModal(id=null){',begin);
 assert(begin>0&&end>begin);
 const logic={norm:s=>String(s).toLowerCase().replace(/[^a-z]/g,''),window:{},state:{},$:()=>null};vm.createContext(logic);vm.runInContext(app.slice(begin,end),logic);
 const oldLearn={correct:17,mistakes:4};const word={word:'because',meaningEn:'School worksheet explanation',meaningJa:'',example:'My own example',pictureEmoji:'✦',learn:oldLearn};
 const changed=logic.applyAutoFillFields(word,result,{protectSchoolMeaning:true});
 assert.equal(changed,4,'Only Japanese, picture emoji/cue, and phonics are eligible');
 assert.equal(word.meaningEn,'School worksheet explanation');assert.equal(word.example,'My own example');
 assert.equal(word.meaningJa,'なぜならば、理由を示す');assert.equal(word.learn,oldLearn,'learning history unchanged');
 assert.equal(logic.applyAutoFillFields(word,result,{protectSchoolMeaning:true}),0,'repeat fill is non-destructive');
 console.log('PASS v34: dictionary lookup, cautious translation, no fabricated misses, cached lookups, school definitions protected, 3-group bulk controls, My Words auto, exact audio, backup and learning retained.');
})().catch(e=>{console.error(e);process.exitCode=1});
